version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
# Notes:
# - This setup exposes frontend on port 80 and backend on 3000.
# - For production use behind a domain, consider an external reverse proxy (nginx/Traefik) with TLS.
