name: Publish

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish:
    name: Publish packages (Changesets)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the built-in GITHUB_TOKEN or custom PAT if you need publishing to external registries
          npx changeset publish --yes
