name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend
        working-directory: dev/frontend
        run: |
          npm install
          npm run build

      - name: Copy files to droplet via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: .
          target: ~/faq-chatbot
          rm: true

      - name: Run deploy script on droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/faq-chatbot/dev/backend
            npm install
            pm2 restart faq-chatbot || pm2 start server.js --name faq-chatbot
            cd ~/faq-chatbot/dev/frontend
            npm install
            npm run build

            # Ensure NGINX live folder exists and is owned by www-data
            sudo mkdir -p /var/www/faq-chatbot
            sudo chown -R www-data:www-data /var/www/faq-chatbot

            # Copy build to NGINX live folder
            sudo rm -rf /var/www/faq-chatbot/* || true
            sudo cp -r dist/* /var/www/faq-chatbot/
            sudo chown -R www-data:www-data /var/www/faq-chatbot

            # Reload nginx
            sudo systemctl reload nginx || true
